sonar.projectKey=fleet-management-frontend
sonar.projectName=fleet-management-frontend
sonar.sources=src
sonar.exclusions=**/node_modules/**,**/dist/**,src/app/pages/documents/driver-document-details.spec.ts,src/app/pages/documents/mission-document-details.spec.ts,src/app/pages/documents/vehicle-document-details.spec.ts
sonar.javascript.lcov.reportPaths=coverage/**/lcov.info